# Generated by Django 6.0.4 on 2026-09-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('content', models.TextField()),
                ('title_image', models.ImageField(upload_to='blog/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.profile')),
            ],
        ),
    ]
