# Generated by Django 6.0.4 on 2026-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogannouncement',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
